@ECHO OFF
SET SVN_USERNAME=autobuild_ps
SET SVN_PASSWORD=Qwerty12
SET DOTNETFRAMEWORK=C:\Windows\Microsoft.NET\Framework\v4.0.30319
SET EXCLUDE_FILE_PATTERN=*.pdb
REM SET INCLUDE_FILE_PATTERN=
run %1 %2 %3 %4